import { expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { parseTranscriptFile, extractToolErrors, extractToolUses, extractUserMessages } from "../src/parser";
import { checkSession, loadModel, saveModel } from "../src/model";
import { buildSessionTimeline } from "../src/viz";
import { generateAgentsRules } from "../src/suggestions";
import type { AnalysisReport, ProjectAnalysis, SignalResult } from "../src/types";

const fixturePath = path.join(import.meta.dir, "fixtures", "pi-session.jsonl");

test("parser extracts Pi session messages and tool calls", async () => {
  const events = await parseTranscriptFile(fixturePath);
  expect(events.length).toBeGreaterThan(10);
  expect(extractUserMessages(events)).toEqual([
    "Please update the file and keep going until it is fixed.",
    "wait, only touch src/index.ts",
    "no, stop changing that block and fix the bug instead"
  ]);
  expect(extractToolUses(events)).toHaveLength(6);
  expect(extractToolErrors(events)).toBe(3);
});

test("session check detects Pi-specific anti-patterns", async () => {
  const result = await checkSession(fixturePath, "test-session-123");
  const signalNames = result.activeSignals.map((signal) => signal.signalName);
  expect(signalNames).toContain("error-loop");
  expect(signalNames).toContain("edit-thrashing");
  expect(signalNames).toContain("correction-heavy");
  expect(result.guidance.length).toBeGreaterThan(0);
});

test("timeline rendering metrics stay coherent", async () => {
  const timeline = await buildSessionTimeline(fixturePath);
  expect(timeline.turns.length).toBeGreaterThan(5);
  expect(timeline.healthPercentage).toBeLessThan(100);
  expect(timeline.summary).toContain("tool errors");
});

test("saved model round-trips from .pi-doctor", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-doctor-"));
  const report: AnalysisReport = {
    generatedAt: new Date(),
    totalSessions: 4,
    totalProjects: 1,
    topSignals: [{ signalName: "error-loop", score: -3, severity: "high", details: "3 consecutive failures" }],
    suggestions: ["After 2 consecutive tool failures, stop and change your approach entirely."],
    projects: [
      {
        projectName: "/tmp/pi-doctor-demo",
        projectPath: "/tmp/pi-doctor-demo",
        sessionCount: 4,
        overallScore: -12,
        signals: [{ signalName: "error-loop", score: -3, severity: "high", details: "3 consecutive failures" }]
      }
    ]
  };

  const modelDir = saveModel(report, tempDir);
  expect(modelDir).toEndWith(path.join(tempDir, ".pi-doctor"));
  const model = loadModel(tempDir);
  expect(model).toBeDefined();
  expect(model?.totalSessions).toBe(4);
  expect(model?.signalBaselines["error-loop"]).toBe(1);
});

test("rules output is Pi-branded", () => {
  const repeatedSignal: SignalResult = {
    signalName: "error-loop",
    score: -3,
    severity: "high",
    details: "3 consecutive failures"
  };
  const projects: ProjectAnalysis[] = [
    {
      projectName: "/tmp/pi-doctor-demo",
      projectPath: "/tmp/pi-doctor-demo",
      sessionCount: 3,
      overallScore: -9,
      signals: [repeatedSignal, { ...repeatedSignal, score: -4 }, { ...repeatedSignal, score: -5 }]
    }
  ];

  const rules = generateAgentsRules(projects, 3);

  expect(rules).toContain("auto-generated by pi-doctor");
  expect(rules).toContain("AGENTS.md");
});
