import type { ProjectAnalysis } from "./types";

const aggregateSignals = (projects: ProjectAnalysis[]) => {
  const aggregations = new Map<
    string,
    { signalName: string; count: number; totalScore: number; worstScore: number; affectedProjects: string[] }
  >();

  for (const project of projects) {
    for (const signal of project.signals) {
      const existing = aggregations.get(signal.signalName);
      if (existing) {
        existing.count++;
        existing.totalScore += signal.score;
        existing.worstScore = Math.min(existing.worstScore, signal.score);
        if (!existing.affectedProjects.includes(project.projectName)) existing.affectedProjects.push(project.projectName);
      } else {
        aggregations.set(signal.signalName, {
          signalName: signal.signalName,
          count: 1,
          totalScore: signal.score,
          worstScore: signal.score,
          affectedProjects: [project.projectName]
        });
      }
    }
  }

  return [...aggregations.values()].sort((left, right) => left.totalScore - right.totalScore);
};

export const generateSuggestions = (projects: ProjectAnalysis[]): string[] => {
  const suggestions: string[] = [];
  const aggregated = aggregateSignals(projects);

  for (const aggregation of aggregated) {
    switch (aggregation.signalName) {
      case "edit-thrashing":
        if (aggregation.count >= 2) suggestions.push("Read the full file before editing. Plan all changes, then make one complete edit.");
        break;
      case "error-loop":
        if (aggregation.count >= 3) suggestions.push("After 2 consecutive tool failures, stop and change your approach entirely.");
        break;
      case "negative-sentiment":
      case "correction-heavy":
        if (aggregation.count >= 2) suggestions.push("When the user corrects you, stop and re-read their message before continuing.");
        break;
      case "user-interrupts":
        if (aggregation.count >= 2) suggestions.push("Break work into smaller verifiable steps before making large changes.");
        break;
      case "restart-cluster":
        if (aggregation.count >= 2) suggestions.push("When stuck, summarize what you tried instead of restarting the same approach.");
        break;
      case "excessive-exploration":
        if (aggregation.count >= 3) suggestions.push("Act sooner. Do not read 10 files before making the first useful change.");
        break;
      case "keep-going-loop":
        if (aggregation.count >= 2) suggestions.push("Complete the full task before stopping.");
        break;
      case "repeated-instructions":
        if (aggregation.count >= 2) suggestions.push("Re-read the user’s last message before responding and follow every instruction through.");
        break;
      case "negative-drift":
        if (aggregation.count >= 2) suggestions.push("Every few turns, re-read the original request so you do not drift.");
        break;
      case "rapid-corrections":
        if (aggregation.count >= 2) suggestions.push("Double-check your output before presenting it.");
        break;
      case "high-turn-ratio":
        if (aggregation.count >= 2) suggestions.push("Work more autonomously and make reasonable default decisions.");
        break;
    }
  }

  return suggestions;
};

export const generateAgentsRules = (projects: ProjectAnalysis[], totalSessions: number): string => {
  const rules = generateSuggestions(projects);
  if (rules.length === 0) return "";

  const lines: string[] = [];
  lines.push("## Rules (auto-generated by pi-doctor)");
  lines.push("");
  lines.push(`Based on analysis of ${totalSessions} Pi sessions. Paste into your AGENTS.md or ~/.pi/agent/AGENTS.md.`);
  lines.push("");
  for (const rule of rules) lines.push(`- ${rule}`);
  lines.push("");
  return lines.join("\n");
};
